Repository spryker-shop/b2b-demo-shop, pull requests merged in 2023-03, with the labels that each got.

#129 CC-26039: Add robot test
  .github/workflows/ci.yml
  deploy.ci.acceptance.mariadb.yml
  deploy.ci.acceptance.yml
Labels: enhancement, ready-for-release

#138 CC-25744 Fixed missing number formatting on Sales page.
  src/Pyz/Yves/ExampleProductSalePage/Controller/SaleController.php
  src/Pyz/Yves/ExampleProductSalePage/ExampleProductSalePageDependencyProvider.php
  src/Pyz/Yves/ExampleProductSalePage/ExampleProductSalePageFactory.php
Labels: bug, request-review

#134 SUPESC-603 Fixed product category order overriding during data import
  src/Pyz/Zed/DataImport/Business/Model/ProductAbstract/ProductAbstractHydratorStep.php
Labels: bug, request-review

#136 CC-26185 CC-26347: Fixed scheduled prices concatenation for MariaDB.
  composer.lock
  config/install/docker.ci.acceptance.yml
Labels: bug, ready-for-release

#149 SUPESC-728 Replaced discount product label conditions with IN and NOT IN comparators.
  composer.json
  composer.lock
  src/Pyz/Zed/Discount/DiscountDependencyProvider.php
Labels: bug, ready-for-release

#144 SDK-1815: cleaned up demo shop.
  composer.lock
  src/Pyz/Client/ExampleProductSalePage/ExampleProductSalePageDependencyProvider.php
  src/Pyz/Glue/Log/LogDependencyProvider.php
  src/Pyz/Service/Flysystem/FlysystemDependencyProvider.php
  src/Pyz/Yves/ExampleProductSalePage/ExampleProductSalePageDependencyProvider.php
  src/Pyz/Yves/Log/LogDependencyProvider.php
  src/Pyz/Yves/ProductDetailPage/ProductDetailPageDependencyProvider.php
  src/Pyz/Zed/DataImport/DataImportDependencyProvider.php
Labels: improvement

#142 CC-16906 Adjusted session & token validation.
  composer.json
  composer.lock
  config/Zed/cronjobs/jenkins.php
  src/Orm/Zed/CustomerStorage/Persistence/SpyCustomerInvalidatedStorage.php
  src/Orm/Zed/CustomerStorage/Persistence/SpyCustomerInvalidatedStorageQuery.php
  src/Pyz/Client/Oauth/OauthDependencyProvider.php
  src/Pyz/Client/RabbitMq/RabbitMqConfig.php
  src/Pyz/Yves/ShopApplication/ShopApplicationDependencyProvider.php
  src/Pyz/Zed/Console/ConsoleDependencyProvider.php
  src/Pyz/Zed/Customer/Persistence/Propel/Schema/spy_customer.schema.xml
  src/Pyz/Zed/Publisher/PublisherDependencyProvider.php
  src/Pyz/Zed/Queue/QueueDependencyProvider.php
  src/Pyz/Zed/Synchronization/SynchronizationDependencyProvider.php
Labels: ready-for-release
