Repository spryker-shop/b2b-demo-shop, pull requests merged in 2023-08, with the labels that each got.

#251 CC-30446: Integration CC-24108
  composer.json
  composer.lock
Labels: ready-for-release

#259 CC-21846 Fixed product variant selector on the Cart page.
  composer.lock
  src/Pyz/Yves/CartPage/Theme/default/components/molecules/product-cart-item/product-cart-item.twig
  src/Pyz/Yves/ShopUi/Theme/default/components/molecules/formatted-number-input/formatted-number-input.scss
  src/Pyz/Yves/ShopUi/Theme/default/components/molecules/product-item-variant-selector/product-item-variant-selector.twig
Labels: bug

#261 CC-29896 Introduced Docker container for Robot tests.
  .github/workflows/ci.yml
  .gitignore
  .robot/Dockerfile
  .robot/docker-compose.robot.yml
  composer.lock
  deploy.ci.acceptance.mariadb.yml
  deploy.ci.acceptance.yml
  deploy.dev.yml
Labels: ready-for-release, improvement

#263 CC-26235 Added extension validation for file upload.
  composer.json
  composer.lock
  data/import/common/common/mime_type.csv
  src/Pyz/Zed/FileManagerGui/FileManagerGuiConfig.php
  src/Pyz/Zed/PriceProductScheduleGui/PriceProductScheduleGuiConfig.php
  src/Pyz/Zed/ProductListGui/ProductListGuiConfig.php
Labels: bug, ready-for-release

#265 CC-31060 Update feature aliases
  composer.json
  composer.lock
Labels: bug, ready-for-release
