Repository spryker-shop/b2b-demo-shop, pull requests merged in 2023-10, with the labels that each got.

#284 CC-31482 Update the oryx-for-zed dependency
  package-lock.json
  package.json
Labels: dependencies

#288 CC-29874 Updated `npm` dependencies.
  composer.lock
  package-lock.json
  package.json
Labels: dependencies

#285 CC-31029 Fixed exception for deactivated products in cart integration.
  composer.json
  composer.lock
  src/Pyz/Yves/CartPage/CartPageDependencyProvider.php
Labels: bug

#290 SUPESC-780 Fixed failing automated tests on local environment.
  deploy.dev.yml
  tests/PyzTest/Yves/Application/Presentation/Controller/HomepageCest.php
  tests/PyzTest/Yves/Application/_support/ApplicationPresentationTester.php
  tests/PyzTest/Yves/Application/codeception.yml
  tests/PyzTest/Zed/NavigationGui/Presentation/NavigationCRUDCest.php
  tests/PyzTest/Zed/NavigationGui/_support/NavigationGuiPresentationTester.php
  tests/PyzTest/Zed/Product/Business/ProductAbstractManagerTest.php
  tests/PyzTest/Zed/Product/Business/ProductConcreteManagerTest.php
  tests/PyzTest/Zed/ProductRelation/Presentation/ProductRelationCreateRelationCest.php
  tests/PyzTest/Zed/ProductRelation/_support/PageObject/ProductRelationCreatePage.php
  tests/PyzTest/Zed/ProductRelation/_support/ProductRelationPresentationTester.php
Labels: bug, ready-for-release

#293 CC-31574 Update npm dependencies
  package-lock.json
Labels: dependencies

#291 FRW-6379: Synchronize cors-allow-origin property
  deploy.dev.yml
Labels: bug, ready-for-release

#307 FRW-6504 Adjusted Data Exchange API configuration file.
  src/Pyz/Zed/DynamicEntity/data/installer/configuration.json
Labels: bug

#310 CC-31686 Docker CI fix integration.
  config/Shared/config_default-docker.ci.php
Labels: ready-for-release

#308 CC-31676 Updated tooling configuration for NPM evaluator.
  composer.lock
  tooling.yml
Labels: bug, ready-for-release
