Repository spryker-shop/b2b-demo-shop, pull requests merged in 2023-12, with the labels that each got.

#357 CC-32034 Fixed Robot package sync issue.
  .dockersyncignore
Labels: bug

#358 CC-31983 Fixed Agent bar
  package-lock.json
  src/Pyz/Yves/AgentWidget/Theme/default/components/molecules/agent-control-item/agent-control-item.scss
  src/Pyz/Yves/AgentWidget/Theme/default/components/molecules/agent-control-item/agent-control-item.twig
  src/Pyz/Yves/AgentWidget/Theme/default/components/organisms/agent-control-bar/agent-control-bar.scss
  src/Pyz/Yves/AgentWidget/Theme/default/components/organisms/agent-control-bar/agent-control-bar.twig
  src/Pyz/Yves/QuoteRequestAgentWidget/Theme/default/components/atoms/request-button/index.ts
  src/Pyz/Yves/QuoteRequestAgentWidget/Theme/default/components/atoms/request-button/request-button.scss
  src/Pyz/Yves/QuoteRequestAgentWidget/Theme/default/components/atoms/request-button/request-button.twig
  src/Pyz/Yves/QuoteRequestAgentWidget/Theme/default/views/quote-request-agent-overview/quote-request-agent-overview.twig
  src/Pyz/Yves/ShopUi/Theme/default/components/atoms/icon-sprite/icon-sprite.twig
  src/Pyz/Yves/ShopUi/Theme/default/components/atoms/icon/icon.scss
  src/Pyz/Yves/ShopUi/Theme/default/components/molecules/autocomplete-form/autocomplete-form.scss
  src/Pyz/Yves/ShopUi/Theme/default/components/molecules/autocomplete-form/autocomplete-form.twig
  src/Pyz/Yves/ShopUi/Theme/default/components/molecules/logo/logo.twig
  src/Pyz/Yves/ShopUi/Theme/default/components/molecules/menu/menu.scss
  src/Pyz/Yves/ShopUi/Theme/default/components/organisms/navigation-top/navigation-top.scss
  src/Pyz/Yves/ShopUi/Theme/default/templates/page-layout-main/page-layout-main.scss
Labels: bug

#364 CC-32131 Fixed merchant portal and Product configurator build for CI acceptance configuration files.
  config/install/docker.ci.acceptance.robot.yml
  deploy.ci.acceptance.mariadb.robot.yml
Labels: bug

#365 CC-31629 Fixed submit button disabling on the checkout address step.
  composer.lock
  src/Pyz/Yves/CheckoutPage/Theme/default/components/molecules/address-item-form-field-list/address-item-form-field-list.twig
  src/Pyz/Yves/CheckoutPage/Theme/default/components/molecules/address-item-form/address-item-form.twig
  src/Pyz/Yves/CheckoutPage/Theme/default/views/address/address.twig
  src/Pyz/Yves/CompanyWidget/Theme/default/views/company-business-unit-address/company-business-unit-address.twig
  src/Pyz/Yves/ShopUi/Theme/default/components/molecules/toggler-checkbox/index.ts
  src/Pyz/Yves/ShopUi/Theme/default/components/molecules/toggler-checkbox/toggler-checkbox.ts
  src/Pyz/Yves/ShopUi/Theme/default/components/molecules/toggler-radio/toggler-radio.ts
  src/Pyz/Yves/ShopUi/Theme/default/resources/form/form.twig
Labels: bug

#362 CC-31773 Fixed issue with missing shipment price on Order Details page.
  src/Pyz/Zed/Sales/SalesConfig.php
Labels: bug, ready-for-release

#368 CC-32150 Removed redundant services from robot deploy file.
  deploy.ci.acceptance.mariadb.robot.yml
Labels: ready-for-release, request-review, improvement

#370 CC-32127 Cookies SameSite Lax integration.
  config/Shared/config_default.php
Labels: bug, ready-for-release

#373 CC-30070 Fixed table indents.
  src/Pyz/Yves/ShopUi/Theme/default/components/atoms/table/table.scss
  src/Pyz/Yves/ShopUi/Theme/default/components/molecules/table-action-list/table-action-list.scss
Labels: bug
