Repository spryker-shop/b2b-demo-shop, pull requests merged in 2023-06, with the labels that each got.

#152 CC-26285 Bugfix for packaging units hint
  src/Pyz/Yves/ProductPackagingUnitWidget/Theme/default/components/molecules/measurement-unit/index.ts
  src/Pyz/Yves/ProductPackagingUnitWidget/Theme/default/components/molecules/measurement-unit/measurement-unit.scss
  src/Pyz/Yves/ProductPackagingUnitWidget/Theme/default/components/molecules/packaging-unit-quantity-selector/index.ts
  src/Pyz/Yves/ProductPackagingUnitWidget/Theme/default/components/molecules/packaging-unit-quantity-selector/packaging-unit-quantity-selector.scss
  src/Pyz/Yves/ProductPackagingUnitWidget/Theme/default/components/molecules/packaging-unit-quantity-selector/packaging-unit-quantity-selector.ts
  src/Pyz/Yves/ProductPackagingUnitWidget/Theme/default/components/molecules/packaging-unit-quantity-selector/packaging-unit-quantity-selector.twig
  src/Pyz/Yves/ProductPackagingUnitWidget/Theme/default/components/molecules/product-packaging-new-price/index.ts
  src/Pyz/Yves/ProductPackagingUnitWidget/Theme/default/components/molecules/product-packaging-new-price/product-packaging-new-price.scss
  src/Pyz/Yves/ProductPackagingUnitWidget/Theme/default/views/pdp-product-packaging-unit/pdp-product-packaging-unit.twig
  tsconfig.json
Labels: bug, request-review

#191 CC-25629 Updated Node.js to v18.
  .github/workflows/ci.yml
  .nvmrc
  composer.json
  deploy.aop-b2b-testing.yml
  deploy.aop-demoshop-b2b.yml
  deploy.aws-env-template.yml
  deploy.ci.acceptance.dynamic-store.yml
  deploy.ci.acceptance.mariadb.dynamic-store.yml
  deploy.ci.acceptance.mariadb.prefer-lowest.dynamic-store.yml
  deploy.ci.acceptance.mariadb.yml
  deploy.ci.acceptance.yml
  deploy.ci.api.mariadb.yml
  deploy.ci.api.yml
  deploy.ci.functional.mariadb.yml
  deploy.ci.functional.yml
  deploy.dev.dynamic-store.yml
  deploy.dev.yml
  deploy.dynamic-store.yml
  deploy.yml
  frontend/configs/development.js
  package-lock.json
  package.json
  tsconfig.json
Labels: improvement

#156 CC-16903 Adjusted login mechanism for Backoffice and Merchant Portal.
  composer.json
  composer.lock
  config/Shared/config_default.php
  data/import/common/common/glossary.csv
  src/Pyz/Client/SecurityBlocker/SecurityBlockerDependencyProvider.php
  src/Pyz/Zed/ErrorHandler/ErrorHandlerConfig.php
  src/Pyz/Zed/EventDispatcher/EventDispatcherDependencyProvider.php
Labels: bug, ready-for-release

#193 CC-23397: Added resource relationship support for Backend API.
  src/Pyz/Glue/DocumentationGeneratorApi/DocumentationGeneratorApiDependencyProvider.php
Labels: bug, request-review

#204 CC-29493 Added the robotframework-suite-tests repository to dependencies
  composer.json
  composer.lock
Labels: dependencies, ready-for-release, improvement

#209 CC-29685: Adjusted installation configuration to fix an issue on AT store.
  config/install/docker.yml
Labels: bug, ready-for-release

#211 CC-29660 Fixed displaying approval statuses on shipping cart
  src/Pyz/Client/MultiCart/MultiCartConfig.php
Labels: bug, ready-for-release

#216 CC-29908 Raised date time configurator version
  composer.json
  composer.lock
Labels: ready-for-release

#214 CC-21301: Fixed invalid checkout payment
  composer.lock
  src/Pyz/Zed/CartCode/CartCodeDependencyProvider.php
Labels: bug, ready-for-release
