Repository spryker-shop/b2b-demo-shop, pull requests merged in 2023-11, with the labels that each got.

#315 CC-31726 Update npm dependencies
  composer.lock
  package-lock.json
  package.json
Labels: bug, dependencies

#312 FRW-998 updated PHP version
  .github/workflows/ci.yml
  .scrutinizer.yml
  README.md
  composer.json
  composer.lock
  deploy.aop-b2b-testing.yml
  deploy.aop-consultant.yml
  deploy.aop-demoshop-b2b.yml
  deploy.aws-env-template.yml
  deploy.ci.acceptance.dynamic-store.yml
  deploy.ci.acceptance.mariadb.dynamic-store.yml
  deploy.ci.acceptance.mariadb.yml
  deploy.ci.acceptance.yml
  deploy.ci.api.dynamic-store.yml
  deploy.ci.api.mariadb.dynamic-store.yml
  deploy.ci.api.mariadb.yml
  deploy.ci.api.yml
  deploy.ci.functional.dynamic-store.yml
  deploy.ci.functional.mariadb.dynamic-store.yml
  deploy.ci.functional.mariadb.yml
  deploy.ci.functional.yml
  deploy.dev.dynamic-store.yml
  deploy.dev.yml
  deploy.dynamic-store.yml
  deploy.yml
  phpcs.xml
  src/Pyz/Yves/ContentProductSetWidget/Twig/ContentProductSetTwigFunctionProvider.php
  src/Pyz/Zed/CustomerAccessGui/Communication/Form/CustomerAccessForm.php
  src/Pyz/Zed/CustomerAccessGui/Communication/Form/DataProvider/CustomerAccessDataProvider.php
  tests/PyzTest/Yves/Checkout/Process/Steps/AddressStepTest.php
Labels: improvement

#321 CC-31774 Fixed missing date of birth field in invoice payment.
  src/Pyz/Yves/DummyPayment/DummyPaymentFactory.php
  src/Pyz/Yves/DummyPayment/Form/InvoiceSubForm.php
Labels: bug

#322 SUPESC-754 Fixed Shopping Lists unsharing.
  composer.json
  composer.lock
Labels: bug

#324 CC-31801 Fixed exception when setting merchant relation price.
  src/Pyz/Zed/ProductManagement/Presentation/_partials/product_volume_price_action_button.twig
Labels: ready-for-release

#325 FRW-6810 Fixed config file for DDE API
  src/Pyz/Zed/DynamicEntity/data/installer/configuration.json
Labels: bug

#328 CC-31780 Fixed caching of categories in discounts.
  composer.json
  composer.lock
Labels: bug

#327 CC-31785 Fixed preselected address state for multiple addresses at checkout
  composer.json
  composer.lock
  src/Pyz/Yves/CheckoutPage/Theme/default/components/molecules/address-item-form-field-list/address-item-form-field-list.twig
  src/Pyz/Yves/CheckoutPage/Theme/default/views/address/address.twig
Labels: bug

#330 CC-25879 Decreased memory usage in product data import.
  src/Pyz/Zed/DataImport/Business/DataImportBusinessFactory.php
  src/Pyz/Zed/DataImport/Business/Model/Product/Repository/ProductRepository.php
  src/Pyz/Zed/DataImport/Business/Model/Product/Repository/ProductRepositoryInterface.php
  src/Pyz/Zed/DataImport/Business/Model/ProductConcrete/ProductConcreteAttributesUniqueCheckStep.php
  src/Pyz/Zed/DataImport/DataImportConfig.php
Labels: bug

#331 CC-31782 Fixed address state for multiple addresses
  src/Pyz/Yves/CheckoutPage/Theme/default/components/molecules/address-item-form-field-list/address-item-form-field-list.twig
Labels: bug, ready-for-release

#335 CC-26145: Enhance Comment Validation for User-Specific Orders/Quotes
  composer.json
  composer.lock
  src/Pyz/Zed/Comment/CommentDependencyProvider.php
Labels: bug, ready-for-release

#342 Bulk bugfixes integration
  composer.json
  composer.lock
  tests/PyzTest/Glue/ProductConfigurations/RestApi/Fixtures/ProductConfigurationsRestApiFixtures.php
Labels: bug

#343 CC-31839 Fixed multiple addresses state on Checkout.
  composer.json
  composer.lock
  src/Pyz/Yves/CheckoutPage/Theme/default/components/molecules/address-item-form-field-list/address-item-form-field-list.twig
  src/Pyz/Yves/CompanyWidget/Theme/default/views/company-business-unit-address/company-business-unit-address.twig
Labels: bug, ready-for-release

#344 CC-29261 Updated product configuration API validation and CMS API tests.
  composer.json
  composer.lock
Labels: bug
