Repository spryker-shop/b2b-demo-shop, pull requests merged in 2023-05, with the labels that each got.

#174 SUPESC-605: Fix an exception on company user delete
  composer.lock
  src/Pyz/Zed/CompanyUser/CompanyUserDependencyProvider.php
Labels: bug

#182 CC-28282 Enabled runtime events for Backend API.
  src/Pyz/Glue/EventDispatcher/EventDispatcherDependencyProvider.php
  src/Pyz/Glue/GlueBackendApiApplication/GlueBackendApiApplicationDependencyProvider.php
Labels: ready-for-release

#181 CC-28304 Updated Service Point Patch validation.
  config/install/ci.yml
  config/install/development.yml
  config/install/docker.ci.acceptance.yml
  config/install/docker.ci.api.yml
  config/install/docker.ci.functional.yml
  config/install/docker.yml
  config/install/testing.yml
Labels: bug, ready-for-release

#190 CC-26818 Fixed breadcrumbs for a product integration.
  composer.json
  composer.lock
  src/Pyz/Client/ProductCategoryStorage/ProductCategoryStorageDependencyProvider.php
Labels: bug, ready-for-release
