Repository spryker-shop/b2b-demo-shop, pull requests merged in 2023-04, with the labels that each got.

#155 CC-26329 Updated GitHub Actions to use Node.js 16.
  .github/workflows/ci.yml
Labels: improvement

#158 CC-26404 Replaced `tslint` with `eslint` for YVES.
  .eslintrc.js
  .eslintrc.json
  .github/workflows/ci.yml
  .prettierignore
  composer.json
  frontend/libs/tslint.js
  package-lock.json
  package.json
  src/Pyz/Yves/PriceProductVolumeWidget/Theme/default/components/molecules/volume-price/volume-price.ts
  src/Pyz/Yves/ProductPackagingUnitWidget/Theme/default/components/molecules/packaging-unit-quantity-selector/packaging-unit-quantity-selector.ts
  src/Pyz/Yves/ProductSearchWidget/Theme/default/components/molecules/product-search-autocomplete-form/product-search-autocomplete-form.ts
  src/Pyz/Yves/QuickOrderPage/Theme/default/components/molecules/quick-order-row/quick-order-row.ts
  src/Pyz/Yves/QuoteRequestAgentPage/Theme/default/components/molecules/source-price-form/source-price-form.ts
  src/Pyz/Yves/ShopUi/Theme/default/components/molecules/autocomplete-form/autocomplete-form.ts
  src/Pyz/Yves/ShopUi/Theme/default/components/molecules/breakpoint-dependent-block-placer/breakpoint-dependent-block-placer.ts
  src/Pyz/Yves/ShopUi/Theme/default/components/molecules/custom-select/custom-select.ts
  src/Pyz/Yves/ShopUi/Theme/default/components/molecules/node-animator/node-animator.ts
  src/Pyz/Yves/ShopUi/Theme/default/components/molecules/quantity-counter/quantity-counter.ts
  src/Pyz/Yves/ShopUi/Theme/default/components/molecules/range-slider/range-slider.ts
  src/Pyz/Yves/ShopUi/Theme/default/components/molecules/sticky-body-toggler/sticky-body-toggler.ts
  src/Pyz/Yves/ShopUi/Theme/default/components/molecules/suggest-search/suggest-search-extended.ts
  src/Pyz/Yves/ShopUi/Theme/default/components/molecules/toggler-radio/toggler-radio.ts
  src/Pyz/Yves/ShoppingListNoteWidget/Theme/default/components/molecules/shopping-list-note-toggler/shopping-list-note-toggler.ts
  tslint.json
Labels: ready-for-release

#162 CC-4006 Fixed exception when uploading files with File Manager.
  src/Pyz/Service/FileSystem/FileSystemDependencyProvider.php
Labels: bug, ready-for-release

#164 CC-26742 Fixed Robot CI configuration.
  .github/workflows/ci.yml
Labels: bug, ready-for-release

#147 CC-23635 Added optimisations to handle product bundle on cart page.
  composer.json
  composer.lock
  src/Pyz/Yves/CartPage/Controller/CartController.php
  src/Pyz/Zed/PriceCartConnector/PriceCartConnectorConfig.php
Labels: bug, ready-for-release

#165 CC-24114 Fixed 'print slip' different views.
  composer.json
  composer.lock
  src/Pyz/Yves/SalesReturnPage/Theme/default/views/return-print/return-print.twig
  src/Pyz/Yves/SharedCartWidget/Theme/default/components/molecules/shared-cart-add-product-as-separate-item/shared-cart-add-product-as-separate-item.twig
  src/Pyz/Yves/ShopUi/Theme/default/components/molecules/collapsible-list/collapsible-list.scss
  src/Pyz/Yves/ShopUi/Theme/default/components/molecules/collapsible-list/collapsible-list.twig
Labels: bug
