Repository spryker-shop/b2b-demo-shop, pull requests merged in 2023-07, with the labels that each got.

#226 CC-29960: Added missing mail sender.
  deploy.spryker-b2bintt.yml
Labels: bug

#217 CC-29576 Fixed main search UI issues.
  src/Pyz/Yves/ShopUi/Theme/default/components/molecules/search-form/search-form.scss
  src/Pyz/Yves/ShopUi/Theme/default/components/molecules/search-form/search-form.twig
  src/Pyz/Yves/ShopUi/Theme/default/components/molecules/suggest-search/suggest-search.scss
  src/Pyz/Yves/ShopUi/Theme/default/components/molecules/suggest-search/suggest-search.twig
Labels: bug

#230 CC-29931 Update Sales module
  composer.json
  composer.lock
Labels: bug, request-review

#228 CC-29647 Fixed FE Yves commands.
  .prettierrc.js
  composer_back.json
  frontend/libs/command-line-parser.js
  frontend/libs/formatter.js
  frontend/settings.js
  package-lock.json
  package.json
Labels: bug

#233 CC-30009 Fixed ability to change default price (RFQ).
  src/Pyz/Yves/QuoteRequestAgentPage/Theme/default/components/molecules/source-price-form/source-price-form.ts
  src/Pyz/Yves/QuoteRequestAgentPage/Theme/default/components/molecules/source-price-form/source-price-form.twig
  src/Pyz/Yves/ShopUi/Theme/default/components/atoms/input/input.scss
  src/Pyz/Yves/ShopUi/Theme/default/components/atoms/textarea/textarea.scss
  src/Pyz/Yves/ShopUi/Theme/default/components/molecules/formatted-number-input/formatted-number-input.scss
  src/Pyz/Yves/ShopUi/Theme/default/resources/form/form.twig
Labels: bug

#234 CC-16486 Bugfixes integration
  composer.json
  composer.lock
  src/Pyz/Client/ProductReview/ProductReviewDependencyProvider.php
Labels: bug

#235 CC-30078 Fixed users search for agent
  composer.json
  composer.lock
Labels: bug

#242 CC-16486 Fixed the self-link for the product review resource.
  composer.lock
  src/Pyz/Client/ProductReview/ProductReviewDependencyProvider.php
Labels: bug, ready-for-release

#245 FRW-1992 and FRW-2313 Integration
  composer.json
  composer.lock
Labels: bug, request-review

#244 CC-25992: Adjusted login mechanism for agent and customer.
  composer.lock
  src/Pyz/Yves/SecurityBlockerPage/SecurityBlockerPageConfig.php
Labels: bug

#240 CC-30037: Fixed display shopping cart items count
  src/Pyz/Yves/CartPage/Theme/default/components/molecules/cart-sidebar-item/cart-sidebar-item.twig
  src/Pyz/Yves/CartPage/Theme/default/components/organisms/cart-sidebar/cart-sidebar.twig
  src/Pyz/Yves/CartPage/Theme/default/templates/page-layout-cart-preview/page-layout-cart-preview.twig
  src/Pyz/Yves/CartPage/Theme/default/templates/page-layout-cart/page-layout-cart.twig
Labels: bug, ready-for-release
