Repository spryker-shop/b2b-demo-shop, pull requests merged in 2024-10, with the labels that each got.

#497 FRW-9004 Integration.
  composer.lock
  deploy.ci.acceptance.mariadb.dynamic-store.robot.yml
  src/Pyz/Yves/EventDispatcher/EventDispatcherDependencyProvider.php
Labels: bug, robot-regression-ui-e2e

#501 ACP-3930: Changed OMS to ForeignPaymentB2CStateMachine01
  config/Shared/config_default.php
Labels: robot-regression-ui-e2e

#502 FWR-9121 Fixed broken robot test
  composer.json
  composer.lock
  src/Pyz/Zed/DynamicEntity/DynamicEntityDependencyProvider.php
Labels: skip-robot-regression-ui-e2e

#490 FRW-8878 Integrated router performance issue fix.
  composer.lock
  src/Pyz/Zed/Router/RouterConfig.php
Labels: robot-regression-ui-e2e

#504 FRW-9030 SUPESC Integrations
  composer.lock
Labels: robot-regression-ui-e2e

#505 FRW-7443 Store Context integration.
  composer.lock
  data/import/common/AT/store_context.csv
  data/import/common/DE/store_context.csv
  data/import/common/EU/store_context.csv
  data/import/common/US/store_context.csv
  data/import/common/commerce_setup_import_config_EU.yml
  data/import/common/commerce_setup_import_config_US.yml
  data/import/common/minimal.yml
  data/import/local/full_EU.yml
  data/import/local/full_US.yml
  data/import/production/full_EU.yml
  data/import/production/full_US.yml
  src/Pyz/Client/Store/StoreDependencyProvider.php
  src/Pyz/Zed/Console/ConsoleDependencyProvider.php
  src/Pyz/Zed/DataImport/DataImportDependencyProvider.php
  src/Pyz/Zed/Publisher/PublisherDependencyProvider.php
  src/Pyz/Zed/Store/StoreDependencyProvider.php
  src/Pyz/Zed/StoreContext/Persistence/Propel/Schema/spy_store_context.schema.xml
  src/Pyz/Zed/StoreGui/StoreGuiDependencyProvider.php
Labels: robot-regression-ui-e2e

#507 FRW-9030 Integrations part 4
  composer.json
  composer.lock
Labels: robot-regression-ui-e2e

#506 FRW-8761 Adjusted configuration
  src/Pyz/Zed/DynamicEntity/data/installer/configuration.json
Labels: skip-robot-regression-ui-e2e

#503 FRW-9030 Integrations part 1
  composer.lock
Labels: robot-regression-ui-e2e

#510 FRW-9164 Added extension point to the VariantTable.
  composer.lock
Labels: skip-robot-regression-ui-e2e

#509 FRW-9030 Integrations part 5
  composer.lock
  src/Pyz/Zed/ProductStorage/Persistence/ProductStoragePersistenceFactory.php
Labels: robot-regression-ui-e2e

#512 FRW-1633 Integrations
  .git.docker
  composer.lock
Labels: robot-regression-ui-e2e

#518 CC-34672 Collapsible category tree integraton
  composer.json
  composer.lock
  src/Pyz/Yves/CatalogPage/Theme/default/components/molecules/filter-category/filter-category.scss
  src/Pyz/Yves/CatalogPage/Theme/default/components/molecules/filter-category/filter-category.twig
  src/Pyz/Yves/CatalogPage/Theme/default/templates/page-layout-catalog/page-layout-catalog.twig
Labels: ready-for-release, robot-regression-ui-e2e

#519 FRW-9170: integration
  composer.lock
Labels: robot-regression-ui-e2e

#515 Analytics integration
  composer.json
  composer.lock
  config/Zed/navigation.xml
Labels: skip-robot-regression-ui-e2e

#523 CC-34707 Accessibility issue wrong color on State Machine button in Backoffice
  composer.json
  composer.lock
Labels: skip-robot-regression-ui-e2e

#525 CC-34126 integration.
  composer.json
  composer.lock
  src/Pyz/Client/Permission/PermissionDependencyProvider.php
Labels: robot-regression-ui-e2e

#521 Release 202410.0
  composer.json
  composer.lock
  config/install/docker.ci.functional.yml
  data/import/common/common/glossary.csv
  deploy.aop-b2b-testing.yml
  deploy.aop-consultant.yml
  deploy.aop-demoshop-b2b.yml
  deploy.scos2-b2b.yml
  deploy.spryker-scosb2b.yml
  src/Pyz/Client/Permission/PermissionDependencyProvider.php
  src/Pyz/Zed/Publisher/PublisherDependencyProvider.php
  tests/PyzTest/Yves/Checkout/Process/Steps/SuccessStepTest.php
Labels: robot-regression-ui-e2e

#530 FRW-9241 Adjusted installation configs.
  config/install/ci.yml
  config/install/development.yml
  config/install/docker.ci.acceptance.cypress.yml
  config/install/docker.ci.acceptance.dynamic-store-off.cypress.yml
  config/install/docker.ci.acceptance.dynamic-store-off.robot.yml
  config/install/docker.ci.acceptance.dynamic-store-off.yml
  config/install/docker.ci.acceptance.robot.yml
  config/install/docker.ci.acceptance.yml
  config/install/docker.ci.api.dynamic-store-off.yml
  config/install/docker.ci.api.yml
  config/install/docker.yml
  config/install/testing.yml
Labels: bug, robot-regression-ui-e2e
