Repository spryker-shop/b2b-demo-shop, pull requests merged in 2024-08, with the labels that each got.

#471 CC-34110: Shared cart fatal error integration
  composer.lock
  src/Pyz/Yves/CartPage/Theme/default/templates/page-layout-cart-preview/page-layout-cart-preview.twig
Labels: robot-regression-ui-e2e

#474 ACP-3589: Sales Payment details integration
  composer.json
  composer.lock
  config/Shared/config_default.php
  src/Pyz/Zed/Sales/SalesConfig.php
Labels: skip-robot-regression-ui-e2e

#475 CC-34144: Adjusted GA workflow.
  .github/workflows/robot-ui-e2e-tests.yml
Labels: robot-regression-ui-e2e

#470 ACP-3544: Added merchant protal
  deploy.aop-demoshop-b2b.yml
Labels: improvement, skip-robot-regression-ui-e2e

#477 ACP-3580: Payone ACP App: Klarna Payment Method
  composer.lock
  src/Pyz/Zed/Payment/PaymentConfig.php
Labels: ready-for-release, robot-regression-ui-e2e

#479 FRW-8868 Hackhaton CI.
  .github/workflows/ci.yml
Labels: skip-robot-regression-ui-e2e

#480 FRW-8938 Integration.
  composer.json
  composer.lock
  config/Shared/config_default.php
  src/Pyz/Service/Flysystem/FlysystemDependencyProvider.php
Labels: skip-robot-regression-ui-e2e, hackathon
