Repository spryker-shop/b2b-demo-shop, pull requests merged in 2024-11, with the labels that each got.

#535 ACP-4372: Fixed acp config
  config/Shared/config_default.php
  src/Pyz/Zed/KernelApp/KernelAppDependencyProvider.php
Labels: robot-regression-ui-e2e

#536 CC-34730 Update Summernote dependency
  composer.lock
  package-lock.json
Labels: ready-for-release, robot-regression-ui-e2e

#538 FRW-8773 PHP Unit 11 Support Integration.
  composer.json
  composer.lock
  tests/PyzTest/Glue/PriceProductVolumes/_support/PriceProductVolumesApiTester.php
  tests/PyzTest/Yves/Application/Presentation/Controller/HomepageCest.php
  tests/PyzTest/Yves/Application/_support/ApplicationPresentationTester.php
  tests/PyzTest/Yves/Availability/Presentation/AvailabilityAddToCartCest.php
  tests/PyzTest/Yves/Availability/_support/AvailabilityPresentationTester.php
  tests/PyzTest/Yves/Checkout/Process/Steps/AddressStepTest.php
  tests/PyzTest/Yves/Checkout/Process/Steps/SuccessStepTest.php
  tests/PyzTest/Yves/CompanyUser/Presentation/CompanyRegistrationCest.php
  tests/PyzTest/Yves/CompanyUser/_support/CompanyUserPresentationTester.php
  tests/PyzTest/Yves/Customer/Presentation/CustomerAddressCest.php
  tests/PyzTest/Yves/Customer/Presentation/CustomerAddressesCest.php
  tests/PyzTest/Yves/Customer/Presentation/CustomerLoginCest.php
  tests/PyzTest/Yves/Customer/Presentation/CustomerLogoutCest.php
  tests/PyzTest/Yves/Customer/Presentation/CustomerNewsletterCest.php
  tests/PyzTest/Yves/Customer/Presentation/CustomerOverviewCest.php
  tests/PyzTest/Yves/Customer/Presentation/CustomerProfileCest.php
  tests/PyzTest/Yves/Customer/_support/CustomerPresentationTester.php
  tests/PyzTest/Yves/Newsletter/Presentation/NewsletterSubscriptionCest.php
  tests/PyzTest/Yves/Newsletter/_support/NewsletterPresentationTester.php
  tests/PyzTest/Zed/CmsGui/Presentation/CmsGuiCreatePageCest.php
  tests/PyzTest/Zed/CmsGui/Presentation/CmsGuiPageListCest.php
  tests/PyzTest/Zed/CmsGui/_support/CmsGuiPresentationTester.php
  tests/PyzTest/Zed/Console/Console/ConsoleCest.php
  tests/PyzTest/Zed/MessageBroker/MessageHandlers/Payment/Presentation/PaymentAuthorizedMessageCest.php
  tests/PyzTest/Zed/MessageBroker/MessageHandlers/Payment/Presentation/PaymentCanceledMessageCest.php
  tests/PyzTest/Zed/MessageBroker/MessageHandlers/Payment/Presentation/PaymentCaptureFailedMessageCest.php
  tests/PyzTest/Zed/MessageBroker/MessageHandlers/Payment/Presentation/PaymentCapturedMessageCest.php
  tests/PyzTest/Zed/MessageBroker/MessageHandlers/Payment/Presentation/PaymentRefundFailedMessageCest.php
  tests/PyzTest/Zed/MessageBroker/MessageHandlers/Payment/Presentation/PaymentRefundedMessageCest.php
  tests/PyzTest/Zed/MessageBroker/_support/PaymentPresentationTester.php
  tests/PyzTest/Zed/NavigationGui/Presentation/NavigationCRUDCest.php
  tests/PyzTest/Zed/NavigationGui/Presentation/NavigationTreeCest.php
  tests/PyzTest/Zed/NavigationGui/_support/NavigationGuiPresentationTester.php
  tests/PyzTest/Zed/ProductRelation/Presentation/ProductRelationCreateRelationCest.php
  tests/PyzTest/Zed/ProductRelation/_support/ProductRelationPresentationTester.php
  tests/PyzTest/Zed/Tax/Presentation/TaxRateCreateCest.php
  tests/PyzTest/Zed/Tax/_support/TaxPresentationTester.php
Labels: improvement, robot-regression-ui-e2e

#540 FRW-7399 Fixed product set and product review search stores data.
  .github/workflows/ci.yml
  composer.lock
  src/Pyz/Client/ProductSetPageSearch/ProductSetPageSearchDependencyProvider.php
Labels: bug, robot-regression-ui-e2e

#543 CC-34804 Fixed exception on Manage Company Roles page.
  data/import/common/common/company_role_permission.csv
  data/import/common/common/glossary.csv
Labels: robot-regression-ui-e2e

#544 Integration: CC-20625
  composer.lock
Labels: bug, skip-robot-regression-ui-e2e
