Repository spryker-shop/b2b-demo-shop, pull requests merged in 2024-09, with the labels that each got.

#483 CC-13685: Updated product quantity and total in Mini Cart Widget from catalog AJAX add-to-cart action.
  composer.lock
  src/Pyz/Yves/CartPage/Theme/default/views/product-abstract-add-to-cart-ajax/product-abstract-add-to-cart-ajax.twig
  src/Pyz/Yves/CatalogPage/CatalogPageConfig.php
  src/Pyz/Yves/CatalogPage/Theme/default/templates/page-layout-catalog/page-layout-catalog.twig
  src/Pyz/Yves/ProductWidget/Theme/default/views/catalog-product/catalog-product.twig
  src/Pyz/Yves/ShopUi/Theme/default/components/molecules/product-item/product-item.twig
Labels: request-review, robot-regression-ui-e2e

#484 BUGFIX: Adjusted consultant template
  deploy.aop-consultant.yml
Labels: skip-robot-regression-ui-e2e

#485 FRW-8766 Order matrix performance improvement integration.
  composer.lock
  config/Zed/cronjobs/jenkins.php
  config/Zed/navigation.xml
  src/Orm/Zed/KernelApp/Persistence/SpyAppConfig.php
  src/Orm/Zed/KernelApp/Persistence/SpyAppConfigQuery.php
  src/Pyz/Zed/Console/ConsoleDependencyProvider.php
Labels: skip-robot-regression-ui-e2e

#487 Fixed the Queue Worker stopping too early when using a "stop-when-empty" option.
  composer.lock
  src/Pyz/Zed/Queue/QueueDependencyProvider.php
Labels: bug, skip-robot-regression-ui-e2e

#488 CC-33982: P&S optimisation.
  composer.lock
  src/Pyz/Zed/Console/ConsoleDependencyProvider.php
  src/Pyz/Zed/CustomerAccessStorage/Persistence/Propel/Schema/spy_unauthenticated_customer_access_storage.schema.xml
  src/Pyz/Zed/Event/EventConfig.php
  src/Pyz/Zed/SynchronizationBehavior/SynchronizationBehaviorConfig.php
  src/Pyz/Zed/TaxProductStorage/Persistence/Propel/Schema/spy_tax_product_storage.schema.xml
Labels: request-review, robot-regression-ui-e2e

#489 FRW-7903 Integration
  composer.lock
  src/Pyz/Zed/Product/ProductConfig.php
Labels: bug, skip-robot-regression-ui-e2e

#492 CC-26445 Integration
  src/Pyz/Yves/CustomerPage/CustomerPageConfig.php
Labels: bug, skip-robot-regression-ui-e2e

#493 FRW-8801 Added PHP 8.3 support.
  .github/workflows/ci.yml
  .github/workflows/robot-ui-e2e-tests.yml
  .scrutinizer.yml
  README.md
  composer.json
  composer.lock
  deploy.aws-env-template.yml
  deploy.ci.acceptance.dynamic-store.yml
  deploy.ci.acceptance.mariadb.cypress.yml
  deploy.ci.acceptance.mariadb.dynamic-store.cypress.yml
  deploy.ci.acceptance.mariadb.dynamic-store.robot.yml
  deploy.ci.acceptance.mariadb.dynamic-store.yml
  deploy.ci.acceptance.mariadb.prefer-lowest.dynamic-store.yml
  deploy.ci.acceptance.mariadb.yml
  deploy.ci.acceptance.yml
  deploy.ci.api.dynamic-store.yml
  deploy.ci.api.mariadb.dynamic-store.robot.yml
  deploy.ci.api.mariadb.dynamic-store.yml
  deploy.ci.api.mariadb.yml
  deploy.ci.api.yml
  deploy.ci.functional.dynamic-store.yml
  deploy.ci.functional.mariadb.dynamic-store.yml
  deploy.ci.functional.mariadb.prefer-lowest.dynamic-store.yml
  deploy.ci.functional.mariadb.yml
  deploy.ci.functional.yml
  deploy.dev.dynamic-store.yml
  deploy.dev.yml
  deploy.dynamic-store.yml
  deploy.scos2-b2b.yml
  deploy.spryker-scosb2b.yml
  deploy.yml
  phpcs.xml
Labels: improvement, robot-regression-ui-e2e
