Repository spryker-shop/b2b-demo-shop, pull requests merged in 2024-12, with the labels that each got.

#542 ACP-4516: External search events
  composer.json
  composer.lock
  package-lock.json
  package.json
  src/Pyz/Yves/CartPage/Theme/default/components/molecules/product-cart-item/product-cart-item.twig
  src/Pyz/Yves/CartPage/Theme/default/templates/page-layout-cart/page-layout-cart.twig
  src/Pyz/Yves/CatalogPage/Theme/default/components/molecules/filter-category/filter-category.twig
  src/Pyz/Yves/CheckoutPage/Theme/default/templates/page-layout-order-submitted/page-layout-order-submitted.twig
  src/Pyz/Yves/EventDispatcher/EventDispatcherDependencyProvider.php
  src/Pyz/Yves/ProductDetailPage/Theme/default/components/molecules/variant-configurator/variant-configurator.twig
  src/Pyz/Yves/ProductSearchWidget/Theme/default/components/molecules/product-search-autocomplete-form/product-search-autocomplete-form.twig
  src/Pyz/Yves/ProductSearchWidget/Theme/default/views/product-quick-add/product-quick-add.twig
  src/Pyz/Yves/ProductSetDetailPage/Theme/default/views/set-detail/set-detail.twig
  src/Pyz/Yves/QuickOrderPage/Theme/default/components/molecules/quick-order-row-partial/quick-order-row-partial.twig
  src/Pyz/Yves/ShopApplication/ShopApplicationDependencyProvider.php
  src/Pyz/Yves/ShopUi/Theme/default/components/molecules/product-item/product-item.twig
  src/Pyz/Yves/ShopUi/Theme/default/templates/page-layout-main/page-layout-main.twig
  src/Pyz/Yves/Twig/TwigDependencyProvider.php
  tests/PyzTest/Zed/MessageBroker/MessageHandlers/SearchHttp/Communication/SearchEndpointMessageTest.php
  tests/PyzTest/Zed/MessageBroker/_support/SearchHttpCommunicationTester.php
  tests/PyzTest/Zed/MessageBroker/codeception.yml
Labels: robot-regression-ui-e2e

#546 ACP-4455: Express checkout infrastructure integration.
  composer.json
  composer.lock
  config/Shared/config_default.php
  data/import/common/common/glossary.csv
  src/Pyz/Glue/GlueApplication/GlueApplicationConfig.php
  src/Pyz/Glue/GlueApplication/GlueApplicationDependencyProvider.php
  src/Pyz/Yves/CartPage/Theme/default/components/molecules/cart-summary/cart-summary.twig
  src/Pyz/Yves/CheckoutPage/CheckoutPageConfig.php
  src/Pyz/Yves/CheckoutPage/CheckoutPageDependencyProvider.php
  src/Pyz/Yves/PaymentAppWidget/PaymentAppWidgetConfig.php
  src/Pyz/Yves/Router/RouterDependencyProvider.php
  src/Pyz/Yves/ShopApplication/ShopApplicationDependencyProvider.php
  src/Pyz/Zed/Cart/CartDependencyProvider.php
  src/Pyz/Zed/Checkout/CheckoutDependencyProvider.php
  src/Pyz/Zed/MessageBroker/MessageBrokerDependencyProvider.php
  src/Pyz/Zed/Payment/PaymentDependencyProvider.php
  src/Pyz/Zed/PaymentApp/PaymentAppDependencyProvider.php
  src/Pyz/Zed/PaymentAppShipment/PaymentAppShipmentConfig.php
  src/Pyz/Zed/PaymentCartConnector/PaymentCartConnectorConfig.php
Labels: robot-regression-ui-e2e

#551 ACP-4455: Changed the URL for the cart clean-up.
  src/Pyz/Yves/PaymentAppWidget/PaymentAppWidgetConfig.php
Labels: robot-regression-ui-e2e

#553 ACP-4615: Update of the modules.
  composer.lock
Labels: ready-for-release

#560 ACP-4615: Update of the modules.
  composer.lock
Labels: robot-regression-ui-e2e

#545 FRW-7936 Integration.
  composer.lock
  config/Shared/config_default.php
  src/Pyz/Yves/Router/RouterConfig.php
  src/Pyz/Yves/Router/RouterDependencyProvider.php
  src/Pyz/Yves/StorageRouter/StorageRouterConfig.php
  src/Pyz/Yves/StorageRouter/StorageRouterDependencyProvider.php
  src/SprykerConfig/CodeBucketConfig.php
  tests/PyzTest/Yves/Customer/Presentation/CustomerOverviewCest.php
  tests/PyzTest/Yves/Customer/_support/CustomerPresentationTester.php
  tests/PyzTest/Yves/Customer/_support/PageObject/CustomerOverviewPage.php
Labels: improvement, robot-regression-ui-e2e

#563 SUPESC-859 Updated composer
  composer.lock
Labels: robot-regression-ui-e2e

#566 CC-14130: Fix memory leak on Backoffice ODP page with 100+ items.
  composer.lock
Labels: bug, request-review, skip-robot-regression-ui-e2e

#565 CC-34335: update webpack
  package-lock.json
  package.json
Labels: skip-robot-regression-ui-e2e

#562 FRW-9287 Added new twig var dumper plugin.
  composer.lock
  src/Pyz/Yves/Twig/TwigDependencyProvider.php
  src/Pyz/Zed/Twig/TwigDependencyProvider.php
Labels: skip-robot-regression-ui-e2e

#567 SUPESC-897 Improved performance of BundledProductTable.
  composer.lock
Labels: bug, skip-robot-regression-ui-e2e

#569 CC-35021: Updated cypress hash.
  composer.lock
  package-lock.json
Labels: bug, skip-robot-regression-ui-e2e

#568 FRW-9071 Integration.
  composer.lock
  data/import/common/common/glossary.csv
  src/Pyz/Glue/CustomersRestApi/Validation/customers.validation.yaml
  src/Pyz/Yves/CustomerPage/CustomerPageConfig.php
  src/Pyz/Zed/Customer/CustomerConfig.php
  tests/PyzTest/Glue/Customer/RestApi/CustomerPasswordCest.php
  tests/PyzTest/Glue/Customer/RestApi/CustomerRegistrationCest.php
  tests/PyzTest/Glue/Customer/RestApi/CustomerRestorePasswordCest.php
  tests/PyzTest/Glue/Customer/RestApi/CustomerUpdateCest.php
  tests/PyzTest/Yves/CompanyUser/_support/PageObject/CompanyRegistrationPage.php
Labels: improvement, robot-regression-ui-e2e

#549 FRW-9013 Integration.
  composer.lock
  src/Pyz/Zed/Customer/CustomerConfig.php
Labels: robot-regression-ui-e2e

#550 FRW-9206 Improvement of artefact storage mechanism.
  .github/workflows/ci.yml
  .github/workflows/robot-ui-e2e-tests.yml
Labels: improvement, robot-regression-ui-e2e

#574 FRW-9641 Integration
  composer.lock
  src/Pyz/Glue/CustomersRestApi/Validation/customers.validation.yaml
  src/Pyz/Yves/ExampleProductSalePage/Controller/SaleController.php
  tests/PyzTest/Glue/Customer/RestApi/CustomerPasswordCest.php
  tests/PyzTest/Glue/Customer/RestApi/CustomerRegistrationCest.php
  tests/PyzTest/Glue/Customer/RestApi/CustomerRestorePasswordCest.php
  tests/PyzTest/Glue/Customer/RestApi/CustomerUpdateCest.php
Labels: enhancement, robot-regression-ui-e2e

#579 FRW-9475 Fixed issue with new entity saving for DataExchangeAPI child relations.
  composer.lock
  src/Pyz/Zed/DynamicEntity/data/installer/configuration.json
Labels: robot-regression-ui-e2e

#575 FRW-922 Upgraded predis library to version 2.3.0.
  composer.lock
Labels: improvement, robot-regression-ui-e2e

#578 ACP-4631: MessageBus observability improvement
  composer.json
  composer.lock
Labels: skip-robot-regression-ui-e2e
