Repository spryker-shop/b2b-demo-shop, pull requests merged in 2025-01, with the labels that each got.

#572 CC-34955 Update plotly dependency
  composer.lock
  package-lock.json
Labels: dependencies, robot-regression-ui-e2e

#580 FRW-9686 Integrations
  .git.docker
  composer.json
  composer.lock
  config/Shared/config_default.php
  config/install/ci.yml
  config/install/development.yml
  config/install/docker.ci.acceptance.cypress.yml
  config/install/docker.ci.acceptance.dynamic-store-off.cypress.yml
  config/install/docker.ci.acceptance.dynamic-store-off.robot.yml
  config/install/docker.ci.acceptance.dynamic-store-off.yml
  config/install/docker.ci.acceptance.robot.yml
  config/install/docker.ci.acceptance.yml
  config/install/docker.ci.api.dynamic-store-off.yml
  config/install/docker.ci.api.yml
  config/install/docker.yml
  config/install/testing.yml
  data/import/common/common/glossary.csv
  src/Pyz/Zed/Checkout/CheckoutDependencyProvider.php
  src/Pyz/Zed/Console/ConsoleDependencyProvider.php
Labels: robot-regression-ui-e2e

#583 Upgradebot/upgrade for head release group 5713
  composer.lock
Labels: skip-robot-regression-ui-e2e
