Repository spryker-shop/b2b-demo-shop, pull requests merged in 2025-10, with the labels that each got.

#875 CC-36460: Fix SSP Cypress logic
  .github/workflows/ci.yml
Labels: run-ui-ci

#873 Cart asset FE intergration
  src/Pyz/Yves/SelfServicePortal/Theme/default/components/molecules/asset-selector/asset-selector.scss
  src/Pyz/Yves/SelfServicePortal/Theme/default/views/cart-item-asset-selector/cart-item-asset-selector.twig
  src/Pyz/Yves/ShopUi/Theme/default/components/molecules/product-card-item/product-card-item.twig
Labels: run-compatibility-ci, run-latest-ci

#872 FRW-9141 Integrated Trufflehog Secret Scanning into CI.
  .github/workflows/ci.yml
Labels: improvement

#882 [CC-36434]: Reconfigure CI to run compatibility checks weekly
  .github/workflows/ci.yml
  .github/workflows/compatibility-ci-ssp-master.yml
  .github/workflows/compatibility-ci.yml
  .github/workflows/robot-ui-e2e-tests.yml
Labels: run-compatibility-ci
