Repository spryker-shop/b2b-demo-shop, pull requests merged in 2025-07, with the labels that each got.

#687 OPS-4941 Updated RabbitMQ version.
  deploy.aws-env-template.yml
  deploy.ci.acceptance.dynamic-store-off.yml
  deploy.ci.acceptance.mariadb.cypress.yml
  deploy.ci.acceptance.mariadb.dynamic-store-off.cypress.yml
  deploy.ci.acceptance.mariadb.dynamic-store-off.robot.yml
  deploy.ci.acceptance.mariadb.dynamic-store-off.yml
  deploy.ci.acceptance.mariadb.prefer-lowest.yml
  deploy.ci.acceptance.mariadb.robot.yml
  deploy.ci.acceptance.mariadb.yml
  deploy.ci.acceptance.robot.yml
  deploy.ci.acceptance.yml
  deploy.ci.api.dynamic-store-off.yml
  deploy.ci.api.mariadb.dynamic-store-off.yml
  deploy.ci.api.mariadb.robot.yml
  deploy.ci.api.mariadb.yml
  deploy.ci.api.yml
  deploy.ci.functional.dynamic-store-off.yml
  deploy.ci.functional.mariadb.dynamic-store-off.yml
  deploy.ci.functional.mariadb.prefer-lowest.yml
  deploy.ci.functional.mariadb.yml
  deploy.ci.functional.yml
  deploy.dev.dynamic-store-off.yml
  deploy.dev.yml
  deploy.dynamic-store-off.yml
  deploy.yml
Labels: improvement, run-static-ci, run-ui-ci, run-api-ci, run-functional-ci, run-latest-ci

#700 FRW-10501: Integration.
  composer.lock
Labels: run-ui-ci, run-latest-ci

#715 CC-35846: Added timezone to Order Table filters.
  composer.lock
  src/Pyz/Zed/Store/StoreDependencyProvider.php
Labels: request-review, run-static-ci

#709 SSP-772 Group cart items on the address step by shipment type.
  data/import/common/AT/merchant_store.csv
  data/import/common/DE/merchant_store.csv
  data/import/common/US/merchant_store.csv
  data/import/common/common/glossary.csv
  data/import/common/common/product_offer_shipment_type.csv
  src/Pyz/Yves/CheckoutPage/CheckoutPageDependencyProvider.php
  src/Pyz/Yves/CheckoutPage/Theme/default/components/molecules/address-item-form-field-list/address-item-form-field-list.twig
  src/Pyz/Yves/CheckoutPage/Theme/default/components/molecules/address-item-form/address-item-form.twig
  src/Pyz/Yves/CheckoutPage/Theme/default/components/molecules/address-wrapper/address-wrapper.scss
  src/Pyz/Yves/CheckoutPage/Theme/default/templates/page-layout-checkout/page-layout-checkout.twig
  src/Pyz/Yves/CheckoutPage/Theme/default/views/address/address.twig
  src/Pyz/Yves/CheckoutPage/Theme/default/views/payment/payment.twig
  src/Pyz/Yves/CheckoutPage/Theme/default/views/shipment/shipment.twig
  src/Pyz/Yves/CheckoutPage/Theme/default/views/summary/summary.twig
  src/Pyz/Yves/ClickAndCollectPageExample/ClickAndCollectPageExampleConfig.php
  src/Pyz/Yves/CustomerPage/CustomerPageDependencyProvider.php
  src/Pyz/Yves/CustomerPage/CustomerPageFactory.php
  src/Pyz/Yves/CustomerPage/Form/CheckoutAddressCollectionForm.php
  src/Pyz/Yves/CustomerPage/Form/DataProvider/CheckoutAddressFormDataProvider.php
  src/Pyz/Yves/ProductDetailPage/Controller/ProductController.php
  src/Pyz/Yves/SelfServicePortal/SelfServicePortalConfig.php
  src/Pyz/Yves/SelfServicePortal/Theme/default/components/molecules/asset-list/asset-list.scss
  src/Pyz/Yves/SelfServicePortal/Theme/default/views/address-form-items-by-shipment-type/address-form-items-by-shipment-type.twig
  src/Pyz/Yves/SelfServicePortal/Theme/default/views/single-address-per-shipment-type/single-address-per-shipment-type.twig
  src/Pyz/Yves/ServicePointWidget/ServicePointWidgetConfig.php
  src/Pyz/Yves/ShipmentTypeWidget/ShipmentTypeWidgetConfig.php
  src/Pyz/Yves/ShopApplication/ShopApplicationDependencyProvider.php
  src/Pyz/Yves/ShopUi/Theme/default/components/atoms/icon-sprite/icon-sprite.twig
  src/Pyz/Yves/ShopUi/Theme/default/components/atoms/icon/icon.scss
Labels: run-latest-ci

#722 Ssp master add cypress ssp env
  .github/workflows/ci.yml
  composer.lock
  deploy.ci.acceptance.mariadb.cypress.yml
  deploy.ci.acceptance.mariadb.dynamic-store-off.cypress.yml
Labels: run-ui-ci

#726 Updated feature alias for all features.
  composer.json
  composer.lock
Labels: run-latest-ci

#725 SSP-923 SSP TechDept Q2.
  config/Shared/config_default.php
  config/Zed/navigation.xml
  src/Pyz/Client/Permission/PermissionDependencyProvider.php
  src/Pyz/Shared/SelfServicePortal/SelfServicePortalConfig.php
  src/Pyz/Yves/SelfServicePortal/SelfServicePortalConfig.php
  src/Pyz/Zed/Permission/PermissionDependencyProvider.php
  src/Pyz/Zed/SelfServicePortal/SelfServicePortalConfig.php
Labels: run-latest-ci

#718 SSP-1240 Fix cypress artefacts uploading.
  .github/workflows/ci.yml
  data/import/common/common/glossary.csv
  src/Pyz/Yves/SelfServicePortal/Theme/default/components/molecules/asset-details-title/asset-details-title.twig
Labels: bug, run-latest-ci

#729 SSP-1333 Fix PDP.
  .github/workflows/ci.yml
  composer.lock
  src/Pyz/Yves/SelfServicePortal/Theme/default/components/molecules/asset-finder/asset-finder.twig
  src/Pyz/Yves/SelfServicePortal/Theme/default/views/asset-info-for-item/asset-info-for-item.twig
Labels: run-latest-ci

#733 SSP-1248: Fixed availability issue with Services on checkout.
  src/Pyz/Zed/ClickAndCollectExample/ClickAndCollectExampleConfig.php
Labels: run-latest-ci

#736 SSP-1333 Fix CI.
  .github/workflows/ci.yml
  .github/workflows/robot-ui-e2e-tests.yml
  composer.json
  composer.lock
  src/Pyz/Yves/CustomerPage/Form/CheckoutAddressCollectionForm.php
  src/Pyz/Yves/SelfServicePortal/Theme/default/components/molecules/service-point-shipment-types/service-point-shipment-types.twig
  src/Pyz/Yves/SelfServicePortal/Theme/default/views/dashboard-inquiry/dashboard-inquiry.twig
Labels: run-compatibility-ci, run-latest-ci

#737 SSP-995 Adjusted SSP permissions.
  composer.lock
  data/import/common/common/company_role.csv
  data/import/common/common/company_role_permission.csv
  data/import/common/common/company_user_role.csv
  data/import/common/common/glossary.csv
Labels: run-compatibility-ci, run-latest-ci

#744 SSP-1376: Update asset-related labels in glossary for clarity.
  data/import/common/common/glossary.csv
Labels: run-latest-ci

#753 FRW-10758 Fixed popup overlap with header
  src/Pyz/Yves/MultiFactorAuth/Theme/default/components/molecules/multi-factor-authentication-handler/multi-factor-authentication-handler.twig
  src/Pyz/Yves/ShopUi/Theme/default/components/molecules/main-popup/index.ts
  src/Pyz/Yves/ShopUi/Theme/default/components/molecules/main-popup/main-popup.scss
  src/Pyz/Yves/ShopUi/Theme/default/components/molecules/main-popup/main-popup.twig
Labels: bug, run-latest-ci

#757 Ssp release 202507.0 upmerge b2b release
  composer.json
  composer.lock
  config/Shared/config_default.php
  data/import/common/common/glossary.csv
  src/Pyz/Yves/AgentPage/Theme/default/views/login/login.twig
  src/Pyz/Yves/CatalogPage/Theme/default/components/molecules/category-card/category-card.twig
  src/Pyz/Yves/CatalogPage/Theme/default/components/molecules/category-list-item/category-list-item.twig
  src/Pyz/Yves/CatalogPage/Theme/default/components/molecules/filter-category/filter-category.twig
  src/Pyz/Yves/CatalogPage/Theme/default/components/molecules/suggestion-links-list/suggestion-links-list.twig
  src/Pyz/Yves/CatalogPage/Theme/default/components/molecules/suggestion-product/suggestion-product.twig
  src/Pyz/Yves/CheckoutPage/Theme/default/templates/page-layout-order-submitted/page-layout-order-submitted.twig
  src/Pyz/Yves/CmsSearchPage/Theme/default/components/molecules/search-cms-results/search-cms-results.twig
  src/Pyz/Yves/CustomerPage/Theme/default/views/login/login.twig
  src/Pyz/Yves/MultiFactorAuth/Theme/default/components/molecules/multi-factor-authentication-handler/multi-factor-authentication-handler.twig
  src/Pyz/Yves/MultiFactorAuth/Theme/default/views/user-set-up-page/user-set-up-page.twig
  src/Pyz/Yves/ProductDetailPage/Theme/default/views/pdp/pdp.twig
  src/Pyz/Yves/ProductSetListPage/Theme/default/components/molecules/product-set-card/product-set-card.twig
  src/Pyz/Yves/QuoteRequestAgentWidget/Theme/default/components/atoms/request-button/request-button.twig
  src/Pyz/Yves/SalesReturnPage/Theme/default/components/molecules/return-overview/return-overview.twig
  src/Pyz/Yves/SharedCartPage/Theme/default/views/cart-share/cart-share.twig
  src/Pyz/Yves/SharedCartPage/Theme/default/views/dismiss-confirm/dismiss-confirm.twig
  src/Pyz/Yves/ShopUi/Theme/default/components/molecules/action-card/action-card.twig
  src/Pyz/Yves/ShopUi/Theme/default/components/molecules/banner/banner.twig
  src/Pyz/Yves/ShopUi/Theme/default/components/molecules/main-popup/main-popup.scss
  src/Pyz/Yves/ShopUi/Theme/default/components/molecules/main-popup/main-popup.twig
  src/Pyz/Yves/ShopUi/Theme/default/components/molecules/navigation-icon-list/navigation-icon-list.twig
  src/Pyz/Yves/ShopUi/Theme/default/components/molecules/navigation-list/navigation-list.twig
  src/Pyz/Yves/ShopUi/Theme/default/components/molecules/navigation-multilevel-node/navigation-multilevel-node.twig
  src/Pyz/Yves/ShopUi/Theme/default/components/molecules/product-card-item/product-card-item.twig
  src/Pyz/Yves/ShopUi/Theme/default/components/molecules/product-item-list/product-item-list.twig
  src/Pyz/Yves/ShopUi/Theme/default/components/molecules/product-item/product-item.twig
  src/Pyz/Yves/ShoppingListPage/Theme/default/views/shopping-list-dismiss-confirm/shopping-list-dismiss-confirm.twig
  src/Pyz/Zed/Transfer/TransferConfig.php
Labels: run-compatibility-ci, run-latest-ci

#761 CC-36099: fixes security issue with node modules
  package-lock.json
Labels: run-static-ci, run-npm-ci

#747 CC-36077: UI fixes after accessibility improvements
  src/Pyz/Yves/CartPage/Theme/default/components/molecules/cart-sidebar-item/cart-sidebar-item.scss
  src/Pyz/Yves/CatalogPage/Theme/default/components/molecules/filter-category/filter-category.scss
  src/Pyz/Yves/CatalogPage/Theme/default/components/molecules/filter-category/filter-category.twig
  src/Pyz/Yves/CatalogPage/Theme/default/components/molecules/suggestion-links-list/suggestion-links-list.scss
  src/Pyz/Yves/CatalogPage/Theme/default/components/molecules/suggestion-product/suggestion-product.scss
  src/Pyz/Yves/CatalogPage/Theme/default/components/organisms/filter-section/filter-section.twig
  src/Pyz/Yves/OrderCustomReferenceWidget/Theme/default/components/molecules/order-custom-reference-form/order-custom-reference-form.twig
  src/Pyz/Yves/PaymentPage/Theme/default/templates/page-layout-payment/page-layout-payment.twig
  src/Pyz/Yves/ProductImageWidget/Theme/default/components/molecules/image-gallery/image-gallery.scss
  src/Pyz/Yves/ProductImageWidget/Theme/default/components/molecules/image-gallery/image-gallery.twig
  src/Pyz/Yves/ShopUi/Theme/default/components/atoms/icon-sprite/icon-sprite.twig
  src/Pyz/Yves/ShopUi/Theme/default/components/atoms/link/link.scss
  src/Pyz/Yves/ShopUi/Theme/default/components/atoms/radio/radio.scss
  src/Pyz/Yves/ShopUi/Theme/default/components/atoms/title/title.scss
  src/Pyz/Yves/ShopUi/Theme/default/components/molecules/custom-select/custom-select.scss
  src/Pyz/Yves/ShopUi/Theme/default/components/molecules/form/form.scss
  src/Pyz/Yves/ShopUi/Theme/default/components/molecules/navigation-multilevel-node/navigation-multilevel-node.twig
  src/Pyz/Yves/ShopUi/Theme/default/components/molecules/pagination/pagination.twig
  src/Pyz/Yves/ShopUi/Theme/default/components/molecules/slick-carousel/slick-carousel.scss
  src/Pyz/Yves/ShopUi/Theme/default/components/molecules/suggest-search/suggest-search.scss
  src/Pyz/Yves/ShopUi/Theme/default/components/molecules/toggler-radio/toggler-radio.scss
  src/Pyz/Yves/ShopUi/Theme/default/components/organisms/footer/footer.scss
  src/Pyz/Yves/ShopUi/Theme/default/components/organisms/header/header.twig
  src/Pyz/Yves/ShopUi/Theme/default/components/organisms/side-drawer/side-drawer.scss
  src/Pyz/Yves/ShopUi/Theme/default/templates/page-layout-main/page-layout-main.twig
Labels: run-ui-ci, run-latest-ci

#762 Removed CustomerReorderWidget.
  composer.json
  composer.lock
  src/Pyz/Yves/CartReorderPage/Theme/default/components/molecules/cart-reorder-form/cart-reorder-form.twig
  src/Pyz/Yves/CustomerPage/Theme/default/components/molecules/order-detail/order-detail.twig
  src/Pyz/Yves/CustomerPage/Theme/default/views/order-detail/order-detail.twig
  src/Pyz/Yves/CustomerReorderWidget/Theme/default/components/molecules/customer-reorder-form/customer-reorder-form.twig
  src/Pyz/Yves/CustomerReorderWidget/Theme/default/views/customer-reorder-form/customer-reorder-form.twig
Labels: run-ui-ci

#759 SSP-1230 fixed demodata issues.
  data/import/common/AT/merchant_product_offer_store.csv
  data/import/common/AT/service_point_store.csv
  data/import/common/AT/shipment_method_store.csv
  data/import/common/AT/shipment_price.csv
  data/import/common/AT/shipment_type_store.csv
  data/import/common/DE/merchant_product_offer_store.csv
  data/import/common/DE/service_point_store.csv
  data/import/common/DE/shipment_method_store.csv
  data/import/common/DE/shipment_price.csv
  data/import/common/DE/shipment_type_store.csv
  data/import/common/US/merchant_product_offer_store.csv
  data/import/common/US/service_point_store.csv
  data/import/common/US/shipment_method_store.csv
  data/import/common/US/shipment_price.csv
  data/import/common/US/shipment_type_store.csv
  data/import/common/common/glossary.csv
  data/import/common/common/marketplace/merchant_product_offer.csv
  data/import/common/common/marketplace/product_offer_stock.csv
  data/import/common/common/marketplace/product_offer_validity.csv
  data/import/common/common/product_offer_service.csv
  data/import/common/common/product_offer_shipment_type.csv
  data/import/common/common/product_shipment_type.csv
  data/import/common/common/service.csv
  data/import/common/common/service_point.csv
  data/import/common/common/service_point_address.csv
  data/import/common/common/service_type.csv
  data/import/common/common/shipment.csv
  data/import/common/common/shipment_method_shipment_type.csv
  data/import/common/common/shipment_type.csv
  data/import/common/common/shipment_type_service_type.csv
  src/Pyz/Yves/CheckoutPage/Theme/default/components/molecules/address-item-form-field-list/address-item-form-field-list.twig
  src/Pyz/Yves/ClickAndCollectPageExample/ClickAndCollectPageExampleConfig.php
  src/Pyz/Yves/SelfServicePortal/SelfServicePortalConfig.php
  src/Pyz/Yves/SelfServicePortal/Theme/default/components/molecules/service-point-shipment-types/service-point-shipment-types.twig
  src/Pyz/Yves/ServicePointWidget/ServicePointWidgetConfig.php
  src/Pyz/Yves/ShipmentTypeWidget/ShipmentTypeWidgetConfig.php
Labels: run-compatibility-ci, run-ui-ci, run-latest-ci

#765 CC-36086 OA. Yves. Order Total is not updated in the Order History table
  composer.json
  composer.lock
Labels: bug, run-ui-ci, run-latest-ci

#766 SSP-1382 updated ssp package
  composer.lock
  data/import/common/common/navigation_node.csv
Labels: run-compatibility-ci, run-latest-ci

#769 FRW 10760 Fixed 404 error on filter by category in dynamic sale category
  src/Pyz/Yves/CatalogPage/Theme/default/components/molecules/filter-category/filter-category.twig
Labels: bug, run-ui-ci, run-latest-ci

#773 Ssp release 202507.0 upmerge latest release
  composer.json
  composer.lock
  composer_back.json
Labels: run-compatibility-ci, run-latest-ci

#771 FRW-10781 Fixed banner link to the Spryker website
  data/import/common/common/glossary.csv
Labels: bug, run-ui-ci, run-latest-ci

#772 SSP-1399: Product Offer Integration into SSP.
  composer.json
  composer.lock
  deploy.ssp-ssp-b2b.yml
  src/Pyz/Client/AvailabilityStorage/AvailabilityStorageDependencyProvider.php
  src/Pyz/Yves/QuickOrderPage/QuickOrderPageDependencyProvider.php
  src/Pyz/Zed/Availability/AvailabilityDependencyProvider.php
  src/Pyz/Zed/Cart/CartDependencyProvider.php
  src/Pyz/Zed/Checkout/CheckoutDependencyProvider.php
  src/Pyz/Zed/Oms/OmsDependencyProvider.php
  src/Pyz/Zed/OmsProductOfferReservation/Persistence/Propel/Schema/spy_oms_product_offer_reservation.schema.xml
  src/Pyz/Zed/PriceProductOffer/Persistence/Propel/Schema/spy_price_product_offer.schema.xml
  src/Pyz/Zed/ProductOfferStock/Persistence/Propel/Schema/spy_product_offer_stock.schema.xml
  src/Pyz/Zed/ProductOfferStock/ProductOfferStockDependencyProvider.php
  src/Pyz/Zed/Sales/SalesDependencyProvider.php
Labels: run-compatibility-ci, run-latest-ci

#775 FRW-10788 Updated cypress tests
  composer.lock
Labels: bug, run-ui-ci

#778 Ssp master upmerge latest master
  composer.lock
  data/import/common/common/glossary.csv
  deploy.ssp-ssp-b2b.yml
Labels: run-compatibility-ci, run-latest-ci

#776 CC-36109: button layout on order details page
  data/import/common/common/glossary.csv
  src/Pyz/Yves/CustomerPage/Theme/default/components/molecules/order-detail/order-detail.twig
  src/Pyz/Yves/SalesOrderAmendmentWidget/Theme/default/components/molecules/order-amendment/order-amendment.twig
  src/Pyz/Yves/ShopUi/Theme/default/components/molecules/action-bar/action-bar.scss
  src/Pyz/Yves/ShopUi/Theme/default/components/molecules/navigation-sidebar-item/navigation-sidebar-item.scss
Labels: run-ui-ci
