Repository spryker-shop/b2b-demo-shop, pull requests merged in 2025-04, with the labels that each got.

#627 Integration: FRW-9661, FRW-9444, FRW-9438
  composer.lock
Labels: run-static-ci, run-latest-ci

#629 CC-26244: [Performance] Quote is validated twice in Yves CartController
  composer.lock
  src/Pyz/Yves/CartPage/CartPageConfig.php
Labels: bug, run-static-ci, run-ui-ci

#633 SUPESC-887: integration
  config/Shared/config_default.php
Labels: run-static-ci

#634 CC-35415: B2B yves range date picker has poor accessibility
  src/Pyz/Yves/CheckoutPage/Theme/default/components/molecules/shipment-sidebar/shipment-sidebar.twig
  src/Pyz/Yves/CustomerPage/Theme/default/components/molecules/order-filters/order-filters.twig
  src/Pyz/Yves/QuoteRequestAgentPage/Theme/default/views/quote-request-edit/quote-request-edit.twig
  src/Pyz/Yves/ShopUi/Theme/default/components/molecules/date-time-picker/date-time-picker.scss
  src/Pyz/Yves/ShopUi/Theme/default/components/molecules/date-time-picker/date-time-picker.ts
  src/Pyz/Yves/ShopUi/Theme/default/components/molecules/date-time-picker/date-time-picker.twig
Labels: run-latest-ci

#635 CC-34245 bootstrap upgrade integration
  composer.lock
  package-lock.json
  package.json
Labels: run-latest-ci
