Repository spryker-shop/b2b-demo-shop, pull requests merged in 2025-06, with the labels that each got.

#672 CC-35461 Order save performance optimization
  composer.lock
  src/Pyz/Zed/Sales/SalesConfig.php
Labels: run-latest-ci

#613 FRW-10093 Use Mailpit as standard mail-catcher.
  .git.docker
  deploy.aop-b2b-testing.yml
  deploy.aop-consultant.yml
  deploy.aop-demoshop-b2b.yml
  deploy.aws-env-template.yml
  deploy.ci.acceptance.dynamic-store-off.yml
  deploy.ci.acceptance.mariadb.cypress.yml
  deploy.ci.acceptance.mariadb.dynamic-store-off.cypress.yml
  deploy.ci.acceptance.mariadb.dynamic-store-off.robot.yml
  deploy.ci.acceptance.mariadb.dynamic-store-off.yml
  deploy.ci.acceptance.mariadb.prefer-lowest.yml
  deploy.ci.acceptance.mariadb.robot.yml
  deploy.ci.acceptance.mariadb.yml
  deploy.ci.acceptance.robot.yml
  deploy.ci.acceptance.yml
  deploy.ci.api.mariadb.robot.yml
  deploy.ci.functional.mariadb.prefer-lowest.yml
  deploy.dev.dynamic-store-off.yml
  deploy.dev.yml
  deploy.dynamic-store-off.yml
  deploy.scos2-b2b.yml
  deploy.spryker-scosb2b.yml
  deploy.yml
Labels: run-compatibility-ci

#678 Fixed failed cypress tests.
  composer.lock
  package-lock.json
Labels: run-ui-ci

#680 Enabled composer cache for CI jobs.
  .github/workflows/ci.yml
  .github/workflows/robot-ui-e2e-tests.yml
  deploy.ci.acceptance.dynamic-store-off.yml
  deploy.ci.acceptance.mariadb.cypress.yml
  deploy.ci.acceptance.mariadb.dynamic-store-off.cypress.yml
  deploy.ci.acceptance.mariadb.dynamic-store-off.robot.yml
  deploy.ci.acceptance.mariadb.dynamic-store-off.yml
  deploy.ci.acceptance.mariadb.prefer-lowest.yml
  deploy.ci.acceptance.mariadb.robot.yml
  deploy.ci.acceptance.mariadb.yml
  deploy.ci.acceptance.robot.yml
  deploy.ci.acceptance.yml
  deploy.ci.api.dynamic-store-off.yml
  deploy.ci.api.mariadb.dynamic-store-off.yml
  deploy.ci.api.mariadb.robot.yml
  deploy.ci.api.mariadb.yml
  deploy.ci.api.yml
  deploy.ci.functional.dynamic-store-off.yml
  deploy.ci.functional.mariadb.dynamic-store-off.yml
  deploy.ci.functional.mariadb.prefer-lowest.yml
  deploy.ci.functional.mariadb.yml
  deploy.ci.functional.yml
Labels: run-compatibility-ci, run-latest-ci

#682 CC-35836: Added queue-based warehouse update functionality.
  composer.json
  composer.lock
  src/Pyz/Zed/Event/EventDependencyProvider.php
  src/Pyz/Zed/Stock/StockConfig.php
Labels: run-latest-ci

#681 Integration: SUPESC-977
  composer.lock
Labels: bug, run-latest-ci
