Repository spryker-shop/b2b-demo-shop, pull requests merged in 2025-03, with the labels that each got.

#607 [All demoshops] Red cypress tests
  composer.lock
  deploy.ci.acceptance.mariadb.cypress.yml
  deploy.ci.acceptance.mariadb.dynamic-store-off.cypress.yml
  package-lock.json
Labels: run-ui-ci

#611 ACP-4150: Added missing PHPDoc description
  src/Pyz/Zed/Publisher/PublisherDependencyProvider.php
Labels: run-static-ci

#610 FRW-10067 Added CustomerEmailChangeRequestWidget widget.
  src/Pyz/Yves/CustomerPage/Theme/default/views/profile/profile.twig
Labels: bug, run-latest-ci

#612 ACP-4690: Added missing message handler
  src/Pyz/Zed/MessageBroker/MessageBrokerConfig.php
  src/Pyz/Zed/MessageBroker/MessageBrokerDependencyProvider.php
Labels: run-static-ci

#609 CC-34127 Added CSRF param to Company Role User form.
  composer.lock
  package-lock.json
Labels: bug, run-static-ci, run-latest-ci

#617 FRW-9988: integration
  composer.lock
Labels: run-static-ci

#623 FRW-9983 Integration
  composer.lock
  config/Shared/config_default.php
  data/import/common/common/cms_block.csv
  data/import/common/common/glossary.csv
  tests/PyzTest/Yves/Customer/Presentation/CustomerProfileCest.php
  tests/PyzTest/Yves/Customer/_support/PageObject/CustomerProfilePage.php
Labels: run-static-ci, run-latest-ci, run-npm-ci
