Repository spryker-shop/b2b-demo-shop, pull requests merged in 2025-05, with the labels that each got.

#639 Update Jenkins version to 2.493.2
  deploy.aop-b2b-testing.yml
  deploy.aop-consultant.yml
  deploy.aop-demoshop-b2b.yml
  deploy.aws-env-template.yml
  deploy.ci.acceptance.mariadb.prefer-lowest.yml
  deploy.ci.functional.mariadb.prefer-lowest.yml
  deploy.dev.dynamic-store-off.yml
  deploy.dev.yml
  deploy.dynamic-store-off.yml
  deploy.scos2-b2b.yml
  deploy.spryker-scosb2b.yml
  deploy.yml
Labels: run-latest-ci

#644 CC-35650 April 2025 integrations.
  composer.lock
  tests/PyzTest/Yves/Checkout/Process/Steps/ShipmentStepTest.php
Labels: run-static-ci, run-latest-ci, run-npm-ci

#653 FRW-10406 Integration.
  composer.json
  composer.lock
  config/Shared/config_default.php
  config/Zed/cronjobs/jenkins.php
  src/Pyz/Yves/Router/RouterDependencyProvider.php
  src/Pyz/Yves/ShopApplication/ShopApplicationDependencyProvider.php
  src/Pyz/Zed/Console/ConsoleDependencyProvider.php
  src/Pyz/Zed/Sitemap/SitemapDependencyProvider.php
Labels: improvement, run-static-ci, run-functional-ci

#654 CC-35509 Remove weekly CI and add run CI on commit to master.
  .github/actions/job-slack-notifications/action.yml
  .github/actions/scheduled-job-slack-notifications/action.yml
  .github/workflows/ci.yml
  .github/workflows/robot-ui-e2e-tests.yml
Labels: run-compatibility-ci, run-latest-ci

#659 CC-35509 Remove label check at static validation ci job.
  .github/workflows/ci.yml
Labels: run-compatibility-ci, run-latest-ci

#662 CC-35775 Remove obsolete CI jobs.
  .github/PULL_REQUEST_TEMPLATE.md
  .github/workflows/ci.yml
  .github/workflows/robot-ui-e2e-tests.yml
Labels: run-compatibility-ci, run-latest-ci

#663 CC-35705 Added search for concrete product SKU for the abstract products section in the Backoffice.
  composer.lock
  src/Pyz/Zed/ProductManagement/ProductManagementConfig.php
Labels: run-static-ci, run-latest-ci

#650 CC-35515 Fixed CompanyBusinessUnitAddressCheckoutDataRestApiCest.
  tests/PyzTest/Glue/Checkout/RestApi/CompanyBusinessUnitAddressCheckoutDataRestApiCest.php
Labels: run-static-ci, run-api-ci, run-latest-ci

#669 CC-35103 Added Apply Scheduled Price and P&S into destructive deployment.
  config/install/destructive.yml
Labels: bug, run-ui-ci
