Repository spryker-shop/b2b-demo-shop, pull requests merged in 2025-08, with the labels that each got.

#787 SUPESC-789 Super attributes don't show values maintained in Backoffice.
  composer.lock
  src/Pyz/Zed/Publisher/PublisherDependencyProvider.php
Labels: run-latest-ci

#790 CC-36115 Integrated bugfixes.
  composer.json
  composer.lock
Labels: run-latest-ci

#791 SSP-1408: Icons button layout
  src/Pyz/Yves/SelfServicePortal/Theme/default/views/inquiry-order-action-button/inquiry-order-action-button.twig
  src/Pyz/Yves/ShopUi/Theme/default/components/atoms/icon-sprite/icon-sprite.twig
  src/Pyz/Yves/ShopUi/Theme/default/templates/page-layout-main/page-layout-main.twig
Labels: run-latest-ci

#793 FRW-10782 Upgraded MFA modules version.
  composer.lock
Labels: improvement, run-static-ci, run-ui-ci, run-latest-ci, run-npm-ci

#784 CC-36099 tests for table filters
  composer.lock
  package-lock.json
Labels: run-ui-ci

#798 CC-36139 Fixing flickery tests.
  composer.lock
Labels: run-ui-ci

#812 SUPESC-864 Switching a discount's type doesn't handle the associated voucher codes.
  composer.lock
  src/Pyz/Zed/Discount/DiscountDependencyProvider.php
Labels: run-latest-ci

#819 Weekly integrations.
  composer.lock
Labels: run-compatibility-ci, run-latest-ci

#825 SUPESC-996 Integration.
  src/Pyz/Glue/Log/LogDependencyProvider.php
  src/Pyz/Yves/Log/LogDependencyProvider.php
  src/Pyz/Zed/Log/LogDependencyProvider.php
Labels: bug, run-functional-ci

#826 ACP-5066: Algolia CMS Pages search integration
  composer.lock
  config/Shared/config_default.php
  src/Pyz/Client/Catalog/CatalogDependencyProvider.php
  src/Pyz/Client/CmsPageSearch/CmsPageSearchDependencyProvider.php
  src/Pyz/Zed/MessageBroker/MessageBrokerDependencyProvider.php
  src/Pyz/Zed/Publisher/PublisherDependencyProvider.php
Labels: run-static-ci, run-ui-ci, run-functional-ci

#824 Upmerge master to ssp master
  .git.docker
  .github/workflows/ci.yml
  .github/workflows/generate-api-docs.yml
  composer.json
  composer.lock
  config/Shared/config_default.php
  config/install/docker.yml
  data/import/common/common/product_image.csv
  data/import/common/common/product_set.csv
  deploy.aop-b2b-testing.yml
  deploy.aop-consultant.yml
  deploy.aop-demoshop-b2b.yml
  deploy.aws-env-template.yml
  deploy.ci.acceptance.dynamic-store-off.yml
  deploy.ci.acceptance.mariadb.cypress.yml
  deploy.ci.acceptance.mariadb.dynamic-store-off.cypress.yml
  deploy.ci.acceptance.mariadb.dynamic-store-off.robot.yml
  deploy.ci.acceptance.mariadb.dynamic-store-off.yml
  deploy.ci.acceptance.mariadb.prefer-lowest.yml
  deploy.ci.acceptance.mariadb.robot.yml
  deploy.ci.acceptance.mariadb.yml
  deploy.ci.acceptance.robot.yml
  deploy.ci.acceptance.yml
  deploy.ci.api.dynamic-store-off.yml
  deploy.ci.api.mariadb.dynamic-store-off.yml
  deploy.ci.api.mariadb.robot.yml
  deploy.ci.api.mariadb.yml
  deploy.ci.api.yml
  deploy.ci.functional.dynamic-store-off.yml
  deploy.ci.functional.mariadb.dynamic-store-off.yml
  deploy.ci.functional.mariadb.prefer-lowest.yml
  deploy.ci.functional.mariadb.yml
  deploy.ci.functional.yml
  deploy.dev.dynamic-store-off.yml
  deploy.dev.yml
  deploy.dynamic-store-off.yml
  deploy.yml
  package-lock.json
  package.json
  src/Pyz/Service/Monitoring/MonitoringDependencyProvider.php
  src/Pyz/Shared/ProductImage/ProductImageConfig.php
  src/Pyz/Yves/ProductImageWidget/Theme/default/components/molecules/image-gallery/image-gallery.twig
  src/Pyz/Zed/Console/ConsoleDependencyProvider.php
  src/Pyz/Zed/DataImport/Business/DataImportBusinessFactory.php
  src/Pyz/Zed/DataImport/Business/Model/ProductImage/Writer/ProductImagePropelDataSetWriter.php
  src/Pyz/Zed/DataImport/Business/Model/ProductSet/ProductSetImageExtractorStep.php
  src/Pyz/Zed/DataImport/Business/Model/ProductSet/ProductSetImageLocalizedAttributesExtractorStep.php
  src/Pyz/Zed/DataImport/Business/Model/ProductSet/ProductSetWriterStep.php
  src/Pyz/Zed/Discount/DiscountDependencyProvider.php
  src/Pyz/Zed/ProductPageSearch/ProductPageSearchDependencyProvider.php
Labels: run-compatibility-ci, run-latest-ci

#828 Upmerge master to ssp master
  .github/workflows/up-merge-latest-master-to-ssp-master.yml
  composer.lock
  config/Shared/config_default.php
  deploy.ci.acceptance.postges.dynamic-store-off.cypress.yml
  src/Pyz/Client/Catalog/CatalogDependencyProvider.php
  src/Pyz/Client/CmsPageSearch/CmsPageSearchDependencyProvider.php
  src/Pyz/Glue/Log/LogDependencyProvider.php
  src/Pyz/Yves/Log/LogDependencyProvider.php
  src/Pyz/Zed/Log/LogDependencyProvider.php
  src/Pyz/Zed/MessageBroker/MessageBrokerDependencyProvider.php
  src/Pyz/Zed/Publisher/PublisherDependencyProvider.php
Labels: run-compatibility-ci, run-latest-ci
