Repository spryker-shop/b2b-demo-shop, pull requests merged in 2025-09, with the labels that each got.

#842 CC-36242 Update cypress-tests path
  .github/workflows/ci.yml
  .gitignore
  composer.json
  composer.lock
  deploy.ci.acceptance.mariadb.cypress.yml
  deploy.ci.acceptance.mariadb.dynamic-store-off.cypress.yml
  deploy.ci.acceptance.postges.dynamic-store-off.cypress.yml
  package-lock.json
Labels: run-latest-ci

#840 SSP-1521 Assets Endless Scroll
  composer.lock
  config/install/destructive.yml
  data/import/common/common/glossary.csv
  data/import/common/common/product_class.csv
  deploy.ssp-ssp-b2b.yml
  package-lock.json
  package.json
  src/Pyz/Client/RabbitMq/RabbitMqConfig.php
  src/Pyz/Yves/CmsSearchPage/Theme/default/components/molecules/search-cms-results/search-cms-results.scss
  src/Pyz/Yves/CmsSearchPage/Theme/default/components/molecules/search-cms-results/search-cms-results.twig
  src/Pyz/Yves/CmsSearchPage/Theme/default/components/molecules/sort/index.ts
  src/Pyz/Yves/CmsSearchPage/Theme/default/components/molecules/sort/sort.scss
  src/Pyz/Yves/CmsSearchPage/Theme/default/components/molecules/sort/sort.twig
  src/Pyz/Yves/CmsSearchPage/Theme/default/templates/search-cms-template/search-cms-template.twig
  src/Pyz/Yves/CmsSearchPage/Theme/default/views/search/search.twig
  src/Pyz/Yves/SelfServicePortal/Theme/default/components/molecules/asset-finder/asset-finder.scss
  src/Pyz/Yves/SelfServicePortal/Theme/default/components/molecules/asset-finder/asset-finder.ts
  src/Pyz/Yves/SelfServicePortal/Theme/default/components/molecules/asset-finder/asset-finder.twig
  src/Pyz/Yves/SelfServicePortal/Theme/default/components/molecules/asset-finder/index.ts
  src/Pyz/Yves/SelfServicePortal/Theme/default/components/molecules/asset-list/asset-list.scss
  src/Pyz/Yves/SelfServicePortal/Theme/default/components/molecules/asset-list/asset-list.twig
  src/Pyz/Yves/SelfServicePortal/Theme/default/components/molecules/asset-list/index.ts
  src/Pyz/Yves/SelfServicePortal/Theme/default/components/molecules/asset-selector/asset-selector.scss
  src/Pyz/Yves/SelfServicePortal/Theme/default/components/molecules/asset-selector/asset-selector.twig
  src/Pyz/Yves/SelfServicePortal/Theme/default/components/molecules/asset-selector/index.ts
  src/Pyz/Yves/SelfServicePortal/Theme/default/views/asset-filter/asset-filter.twig
  src/Pyz/Yves/SelfServicePortal/Theme/default/views/asset-info-for-item/asset-info-for-item.twig
  src/Pyz/Yves/SelfServicePortal/Theme/default/views/item-asset-selector/item-asset-selector.twig
  src/Pyz/Yves/SelfServicePortal/Widget/SspItemAssetSelectorWidget.php
  src/Pyz/Yves/ShopApplication/ShopApplicationDependencyProvider.php
  src/Pyz/Yves/ShopUi/Theme/default/components/molecules/pagination/pagination.scss
  src/Pyz/Yves/ShopUi/Theme/default/components/molecules/pagination/pagination.twig
  src/Pyz/Zed/Console/ConsoleDependencyProvider.php
  src/Pyz/Zed/Publisher/PublisherDependencyProvider.php
  src/Pyz/Zed/Queue/QueueDependencyProvider.php
  src/Pyz/Zed/Transfer/TransferConfig.php
  tests/PyzTest/Zed/TestifyBackendApi/codeception.dynamic.fixtures.yml
Labels: run-latest-ci

#854 SSP-1562 Reduced the number of CI jobs.
  .github/workflows/ci.yml
Labels: run-compatibility-ci, run-latest-ci

#850 FRW-9914 Enable parallel test execution
  .github/workflows/ci.yml
  .github/workflows/robot-ui-e2e-tests.yml
  .robot/Dockerfile
  composer.lock
Labels: run-compatibility-ci, run-ui-ci

#860 SSP-1176: integration
  composer.json
  composer.lock
  config/Shared/config_default-docker.ssp.b2b.php
  src/Orm/Zed/SelfServicePortal/Persistence/SpyCompanyFile.php
  src/Orm/Zed/SelfServicePortal/Persistence/SpyCompanyFileQuery.php
  src/Pyz/Yves/SelfServicePortal/Widget/SspItemAssetSelectorWidget.php
  src/Pyz/Yves/ShopApplication/ShopApplicationDependencyProvider.php
  src/Pyz/Zed/Publisher/PublisherDependencyProvider.php
Labels: run-latest-ci
