Repository spryker-shop/b2b-demo-shop, pull requests merged in 2025-02, with the labels that each got.

#582 FRW-9711 Made CI test execution label-dependent.
  .github/workflows/ci.yml
  .github/workflows/enforce-labels.yml
  .github/workflows/robot-ui-e2e-tests.yml
  composer.lock
Labels: improvement, run-latest-ci

#595 CC-34804: Exception on Manage Company Roles tests
  composer.lock
  package-lock.json
Labels: run-static-ci, run-ui-ci, run-npm-ci

#598 ACP-4696: Integration
  composer.json
  composer.lock
  src/Orm/Zed/TaxApp/Persistence/SpyTaxIdValidationHistory.php
  src/Orm/Zed/TaxApp/Persistence/SpyTaxIdValidationHistoryQuery.php
  src/Pyz/Glue/GlueApplication/GlueApplicationDependencyProvider.php
Labels: run-static-ci, run-functional-ci

#596 CC-35203 Adds datetimepicker js plugin
  composer.lock
  package-lock.json
  package.json
  src/Pyz/Yves/CheckoutPage/Theme/default/components/molecules/shipment-sidebar/shipment-sidebar.twig
  src/Pyz/Yves/ShopUi/Theme/default/components/molecules/date-time-picker/date-time-picker.scss
  src/Pyz/Yves/ShopUi/Theme/default/components/molecules/date-time-picker/date-time-picker.ts
  src/Pyz/Yves/ShopUi/Theme/default/components/molecules/date-time-picker/date-time-picker.twig
Labels: run-static-ci, run-ui-ci

#599 FRW-9083 Integration
  composer.json
  composer.lock
  data/import/common/AT/cms_block_store.csv
  data/import/common/DE/cms_block_store.csv
  data/import/common/US/cms_block_store.csv
  data/import/common/common/cms_block.csv
  data/import/common/common/glossary.csv
  package-lock.json
  src/Orm/Zed/CustomerDataChangeRequest/Persistence/SpyCustomerDataChangeRequest.php
  src/Orm/Zed/CustomerDataChangeRequest/Persistence/SpyCustomerDataChangeRequestQuery.php
  src/Pyz/Yves/LanguageSwitcherWidget/Theme/default/components/molecules/language-switcher/language-switcher.twig
  src/Pyz/Yves/Router/RouterDependencyProvider.php
  src/Pyz/Yves/ShopApplication/ShopApplicationDependencyProvider.php
  src/Pyz/Zed/Customer/CustomerDependencyProvider.php
  src/Pyz/Zed/DynamicEntity/data/installer/configuration.json
  src/Pyz/Zed/Mail/MailDependencyProvider.php
Labels: run-ui-ci, run-latest-ci
